const shoppingBasket = [
  { name: "Ketchup", type: "condiment", quantity: 1, price: 1.2 },
  { name: "Butter", type: "dairy", quantity: 1, price: 1.79 },
  { name: "Ice Cream", type: "frozen", quantity: 2, price: 2.5 },
  { name: "Shampoo", type: "toiletries", quantity: 2, price: 3.25 },
  { name: "Cookies", type: "snacks", quantity: 1, price: 1.19 },
  { name: "Mustard", type: "condiment", quantity: 1, price: 1.36 },
  { name: "Lettuce", type: "vegetables", quantity: 2, price: 0.69 },
  { name: "Honey", type: "condiment", quantity: 1, price: 0.89 },
  { name: "Soup", type: "canned", quantity: 4, price: 0.99 },
  { name: "Onions", type: "vegetables", quantity: 3, price: 0.6 },
  { name: "Fruit", type: "canned", quantity: 3, price: 0.49 },
  { name: "Paper Towels", type: "home", quantity: 2, price: 1.49 },
  { name: "Conditioner", type: "toiletries", quantity: 2, price: 2.65 },
  { name: "Milk", type: "dairy", quantity: 6, price: 0.3 },
  { name: "Freezer Bags", type: "home", quantity: 10, price: 0.59 },
  { name: "Cheese", type: "dairy", quantity: 2, price: 2.24 },
  { name: "Deodorant", type: "toiletries", quantity: 1, price: 1.56 },
  { name: "Apples", type: "fruit", quantity: 6, price: 0.2 },
  { name: "Broccoli", type: "vegetables", quantity: 1, price: 0.52 },
  { name: "Popcorn", type: "snacks", quantity: 3, price: 0.79 },
  { name: "Beer", type: "beverages", quantity: 4, price: 1.1 },
  { name: "Grapes", type: "fruit", quantity: 1, price: 1.2 },
  { name: "Wine", type: "beverages", quantity: 3, price: 4.99 },
  { name: "Bananas", type: "fruit", quantity: 6, price: 0.2 },
  { name: "Cauliflower", type: "vegetables", quantity: 1, price: 0.48 },
];
